# Generated by Django 5.1 on 2024-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
