# Generated by Django 5.1 on 2024-08-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
        migrations.CreateModel(
            name='ImagemAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default=None, upload_to='images/covers/%Y/%m/%d/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
    ]
