# Generated by Django 5.1 on 2024-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_remove_aluno_foto_imagemaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemaluno',
            name='descrição',
            field=models.CharField(default='', max_length=100),
        ),
    ]
