# Generated by Django 5.1 on 2024-08-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_imagemaluno_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemaluno',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
